name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          servers: '[{"id": "jbiobridges", "username": "${{github.actor}}", "password": "${GITHUB_TOKEN}"}]'  
      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
         servers: '[{"id": "jbiobridges", "username": "${{github.actor}}", "password": "${GITHUB_TOKEN}"}]'  
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  