name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build mi-structure
      run: mvn -B package --file mi-structures/pom.xml
      - name: Build mi-bundle
        run: mvn -B package --file mi-bundle/pom.xml
